vvvvv

diff --git a/frontend/build_spec.yaml b/frontend/build_spec.yaml
--- a/frontend/build_spec.yaml
+++ b/frontend/build_spec.yaml
@@ -3,43 +3,50 @@ component: build
 timeoutInSeconds: 6000
 runAs: root
 shell: bash
+env:
+  variables:
+    key: "value"
 
-# Exported variables
-exportedVariables:
-  - BUILDRUN_HASH
+  exportedVariables:
+    - BUILDRUN_HASH
 
 steps:
   - type: Command
-    name: "Define unique image tag"
-    timeoutInSeconds: 40
+    name: "Define Tagging"
+    timeoutInSeconds: 60
     command: |
-      export BUILDRUN_HASH=$(echo ${OCI_BUILD_RUN_ID} | rev | cut -c 1-7)
-      echo "BUILDRUN_HASH: " $BUILDRUN_HASH
+          export BUILDRUN_HASH=$(echo ${OCI_BUILD_RUN_ID} | rev | cut -c 1-7)
+          echo "BUILDRUN_HASH: " $BUILDRUN_HASH
 
     onFailure:
       - type: Command
         command: |
-          echo "Handling Failure"
-          echo "Failure successfully handled"
-        timeoutInSeconds: 40
-        runAs: root
+          echo "Handling Failure in Frontend Build"
+        timeoutInSeconds: 1200
+        runAs: root                 
+      
+  - type: Command
+    name: "Build Frontend Container Image"
+    timeoutInSeconds: 3600
+    command: |
+      cd frontend
+      docker build --pull --rm -t kmlbroker:$BUILDRUN_HASH . || { echo "Frontend build failed"; exit 1; }
+      cd ..
+
 
   - type: Command
-    timeoutInSeconds: 1200
-    name: "Build container image"
+    name: "Build Backend Container Image"
+    timeoutInSeconds: 3600
     command: |
-      # Navigate to frontend directory
-      cd ${OCI_WORKSPACE_DIR}/frontend
-      docker build --pull --rm -t kmlbroker:${BUILDRUN_HASH} .
+      cd backend
+      docker build --pull --rm -t kmlbrokerbe:$BUILDRUN_HASH . || { echo "Backend build failed"; exit 1; }
+      cd ..
+
 
 outputArtifacts:
   - name: frontendImage
     type: DOCKER_IMAGE
     location: kmlbroker:${BUILDRUN_HASH}
-
-# Build Source Configuration
-buildSource:
-  type: Git
-  location: https://github.com/mlsysadmin/kmlbroker.git
-  branchName: main
-  buildSpecFilePath: build_spec.yaml
+  - name: backendImage
+    type: DOCKER_IMAGE
+    location: kmlbrokerbe:${BUILDRUN_HASH}
