3333333

diff --git a/build_spec.yaml b/build_spec.yaml
--- a/build_spec.yaml
+++ b/build_spec.yaml
@@ -13,15 +13,6 @@ env:
     - BUILDRUN_HASH
 
 steps:
-  - name: Authenticate with Kubernetes
-    command: |
-      export KUBECONFIG=/root/.kube/config
-      oci ce cluster create-kubeconfig --cluster-id ocid1.cluster.oc1.ap-tokyo-1.aaaaaaaaxxdjx5bt2bvjgkigvzyqzgpc5tllrtkzmduybc44scgmghlvqbkq --file $HOME/.kube/config --region ap-tokyo-1 --token-version 2.0.0  --kube-endpoint PRIVATE_ENDPOINT
-
-  - name: Ensure Namespace Exists
-    command: |
-      kubectl get namespace kmlbroker || kubectl create namespace kmlbroker
-
   - type: Command
     name: "Define Tagging"
     timeoutInSeconds: 60
@@ -36,6 +27,17 @@ steps:
           echo "Failure successfully handled"
         timeoutInSeconds: 1200
         runAs: root
+
+      - type: Command
+        name: "Ensure Kubernetes Namespace Exists"
+        timeoutInSeconds: 120
+        command: |
+          if ! kubectl get namespace ${K8S_NAMESPACE} >/dev/null 2>&1; then
+            echo "Namespace ${K8S_NAMESPACE} not found. Creating..."
+            kubectl create namespace ${K8S_NAMESPACE}
+          else
+            echo "Namespace ${K8S_NAMESPACE} already exists."
+          fi
 
   - type: Command
     name: "Build container image"
