jjjj

diff --git a/backend/build_spec.yaml b/backend/build_spec.yaml
--- a/backend/build_spec.yaml
+++ b/backend/build_spec.yaml
@@ -14,7 +14,50 @@ steps:
     name: "Login to GitHub Container Registry"
     timeoutInSeconds: 60
     command: |
-      echo "${GHCR_PAT}" | docker login ghcr.io -u "mlsysadmin" --password-stdin
+      version: 0.1
+component: build  # <-- Add this at the root level
+timeoutInSeconds: 6000
+
+steps:
+  - type: Command
+    name: "Define Tagging"
+    timeoutInSeconds: 60
+    command: |
+      export BUILDRUN_HASH=$(echo ${OCI_BUILD_RUN_ID} | rev | cut -c 1-7)
+      echo "BUILDRUN_HASH: " $BUILDRUN_HASH
+
+  - type: Command
+    name: "Login to GitHub Container Registry"
+    timeoutInSeconds: 60
+    command: |
+      echo "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" | docker login ghcr.io -u "mlsysadmin" --password-stdin
+    env:
+      - name: GHCR_PAT
+        valueFrom: "GHCR_PAT_SECRET"
+
+  - type: Command
+    name: "Build Frontend Container Image"
+    timeoutInSeconds: 3600
+    command: |
+      cd frontend
+      docker build --pull --rm -t kmlbroker:$BUILDRUN_HASH . || { echo "Frontend build failed"; exit 1; }
+      cd ..
+
+  - type: Command
+    name: "Build Backend Container Image"
+    timeoutInSeconds: 3600
+    command: |
+      cd backend
+      docker build --pull --rm -t kmlbrokerbe:$BUILDRUN_HASH . || { echo "Backend build failed"; exit 1; }
+      cd ..
+      
+outputArtifacts:
+  - name: frontendImage
+    type: DOCKER_IMAGE
+    location: kmlbroker:${BUILDRUN_HASH}
+  - name: backendImage
+    type: DOCKER_IMAGE
+    location: kmlbrokerbe:${BUILDRUN_HASH}
     env:
       - name: GHCR_PAT
         valueFrom: "GHCR_PAT_SECRET"
